openapi: 3.0.1
info:
  title: Machine Management API
  version: 1.0.0

tags:
  - name: MachineTemplate
    description: Maschinen-Templates verwalten
  - name: AttributeTemplate
    description: Vorlagen für Maschinenattribute
  - name: Machine
    description: Einzelne Maschinen verwalten
  - name: MachineAttribute
    description: Attribute einzelner Maschinen

paths:

  /attribute-templates:
    get:
      tags: [AttributeTemplate]
      summary: Alle AttributeTemplates abrufen
      responses:
        "200":
          description: Liste
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/AttributeTemplateDto"
    post:
      tags: [AttributeTemplate]
      summary: Neues AttributeTemplate erstellen
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/AttributeTemplateDto"
      responses:
        "200":
          description: Erstellt
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/AttributeTemplateDto"

  /attribute-templates/{id}:
    get:
      tags: [AttributeTemplate]
      summary: Einzelnes AttributeTemplate abrufen
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: Einzelnes Attribut
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/AttributeTemplateDto"
    put:
      tags: [AttributeTemplate]
      summary: Attribut aktualisieren
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/AttributeTemplateDto"
      responses:
        "200":
          description: Aktualisiert
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/AttributeTemplateDto"
    delete:
      tags: [AttributeTemplate]
      summary: Attribut löschen
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: Gelöscht

  /machine-attributes:
    get:
      tags: [MachineAttribute]
      summary: Alle Maschinen-Attribute abrufen
      responses:
        "200":
          description: Liste
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/MachineAttributeDto"
    post:
      tags: [MachineAttribute]
      summary: Neues Maschinen-Attribut erstellen
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/MachineAttributeDto"
      responses:
        "200":
          description: Erstellt
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/MachineAttributeDto"
 

  /machine-templates:
    get:
      tags: [MachineTemplate]
      summary: Alle MachineTemplates abrufen
      responses:
        "200":
          description: Liste der Templates
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/MachineTemplateDto"
    post:
      tags: [MachineTemplate]
      summary: Neues MachineTemplate erstellen
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/MachineTemplateDto"
      responses:
        "200":
          description: Erstellt
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/MachineTemplateDto"

  /machine-templates/{id}:
    get:
      tags: [MachineTemplate]
      summary: Einzelnes MachineTemplate abrufen
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: Einzelnes Template
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/MachineTemplateDto"
    put:
      tags: [MachineTemplate]
      summary: Template aktualisieren
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/MachineTemplateDto"
      responses:
        "200":
          description: Aktualisiert
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/MachineTemplateDto"
    delete:
      tags: [MachineTemplate]
      summary: Template löschen
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: Gelöscht

  /attribute-templates:
    get:
      tags: [AttributeTemplate]
      summary: Alle AttributeTemplates abrufen
      responses:
        "200":
          description: Liste
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/AttributeTemplateDto"
    post:
      tags: [AttributeTemplate]
      summary: Neues AttributeTemplate erstellen
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/AttributeTemplateDto"
      responses:
        "200":
          description: Erstellt
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/AttributeTemplateDto"

  /attribute-templates/{id}:
    get:
      tags: [AttributeTemplate]
      summary: Einzelnes AttributeTemplate abrufen
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: Einzelnes Attribut
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/AttributeTemplateDto"
    put:
      tags: [AttributeTemplate]
      summary: Attribut aktualisieren
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/AttributeTemplateDto"
      responses:
        "200":
          description: Aktualisiert
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/AttributeTemplateDto"
    delete:
      tags: [AttributeTemplate]
      summary: Attribut löschen
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: Gelöscht

  /machine-attributes:
    get:
      tags: [MachineAttribute]
      summary: Alle Maschinen-Attribute abrufen
      responses:
        "200":
          description: Liste
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/MachineAttributeDto"
    post:
      tags: [MachineAttribute]
      summary: Neues Maschinen-Attribut erstellen
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/MachineAttributeDto"
      responses:
        "200":
          description: Erstellt
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/MachineAttributeDto"
 /api/machines:
    post:
      summary: Neue Maschine erstellen
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/MachineDto"
      responses:
        "201":
          description: Maschine erstellt
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/MachineDto"

    get:
      summary: Alle Maschinen mit Attributen und Attributwerten laden (eager)
      responses:
        "200":
          description: Maschinenliste
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/MachineDto"

  /api/machines/from-template:
    post:
      summary: Neue Maschine aus Template erzeugen
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateMachineFromTemplateDto"
      responses:
        "201":
          description: Maschine erstellt
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/MachineDto"

  /api/machines/lazy:
    get:
      summary: Alle Maschinen (nur ID, Name, Template)
      responses:
        "200":
          description: Maschinenliste
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/LazyMachineDto"

  /api/machines/{id}:
    get:
      summary: Einzelne Maschine mit Attributen und Attributwerten (eager)
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: Maschine mit Attributen
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/MachineDto"

    put:
      summary: Maschinenname aktualisieren
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/MachineDto"
      responses:
        "200":
          description: Maschine aktualisiert
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/MachineDto"

    delete:
      summary: Maschine löschen
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        "204":
          description: Erfolgreich gelöscht

  /api/machines/{id}/structure:
    get:
      summary: Strukturansicht der Maschine (Attribute, Template-ID)
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: Maschinenstruktur
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/MachineStructureDto"

  /api/machines/{id}/template/{templateId}:
    put:
      summary: Template zu Maschine zuweisen
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
        - name: templateId
          in: path
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: Template zugewiesen
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/MachineDto"

  /api/machines/{id}/template:
    delete:
      summary: Template von Maschine entfernen
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        "204":
          description: Template entfernt

  /machine-attributes/{id}:

    get:
      tags: [MachineAttribute]
      summary: Einzelnes Maschinen-Attribut abrufen
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: Maschinen-Attribut
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/MachineAttributeDto"
    put:
      tags: [MachineAttribute]
      summary: Maschinen-Attribut aktualisieren
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/MachineAttributeDto"
      responses:
        "200":
          description: Aktualisiert
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/MachineAttributeDto"
    delete:
      tags: [MachineAttribute]
      summary: Maschinen-Attribut löschen
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: Gelöscht

  /machine-attributes/{id}:

    get:
      tags: [MachineAttribute]
      summary: Einzelnes Maschinen-Attribut abrufen
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: Maschinen-Attribut
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/MachineAttributeDto"
    put:
      tags: [MachineAttribute]
      summary: Maschinen-Attribut aktualisieren
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/MachineAttributeDto"
      responses:
        "200":
          description: Aktualisiert
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/MachineAttributeDto"
    delete:
      tags: [MachineAttribute]
      summary: Maschinen-Attribut löschen
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: Gelöscht

components:
  schemas:
    AttributeTemplateDto:
      type: object
      properties:
        id:
          type: integer
        attributeInTemplateName:
          type: string
        attributeInTemplateType:
          type: string
          enum: [STRING, INTEGER, FLOAT, BOOLEAN]
      required: [attributeInTemplateName, attributeInTemplateType]

    MachineTemplateDto:
      type: object
      properties:
        id:
          type: integer
        templateName:
          type: string
        attributeTemplates:
          type: array
          items:
            $ref: "#/components/schemas/AttributeTemplateDto"
      required: [templateName, attributeTemplates]

    MachineDto:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        attributes:
          type: array
          items:
            $ref: "#/components/schemas/MachineAttributeDto"
      required: [name, attributes]

    MachineAttributeDto:
      type: object
      properties:
        id:
          type: integer
        attributeName:
          type: string
        attributeType:
          type: string
          enum: [STRING, INTEGER, FLOAT, BOOLEAN]
        attributeValue:
          type: string
        machineId:
          type: integer
      required: [attributeName, attributeType, attributeValue, machineId]
