openapi: 3.0.0
info:
  title: Machine Management API
  version: 1.0.0

paths:
  /machines:
    get:
      summary: Liste aller Maschinen
      responses:
        200:
          description: OK
    post:
      summary: Neue Maschine erstellen
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateMachineDto"
      responses:
        201:
          description: Erstellt

  /machines/{id}:
    get:
      summary: Einzelne Maschine anzeigen
      parameters:
        - $ref: "#/components/parameters/id"
      responses:
        200:
          description: OK
    delete:
      summary: Maschine löschen
      parameters:
        - $ref: "#/components/parameters/id"
      responses:
        204:
          description: Gelöscht

  /machines/{id}/structure:
    get:
      summary: Struktur einer Maschine inkl. Template + Attribute
      parameters:
        - $ref: "#/components/parameters/id"
      responses:
        200:
          description: OK

  /machines/{id}/assign-template:
    post:
      summary: Template zuweisen
      parameters:
        - $ref: "#/components/parameters/id"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                templateId:
                  type: integer
      responses:
        200:
          description: Template zugewiesen

  /machines/{id}/attributes:
    post:
      summary: Attribut zur Maschine hinzufügen
      parameters:
        - $ref: "#/components/parameters/id"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateMachineAttributeDto"
      responses:
        201:
          description: Attribut hinzugefügt

  /machines/{id}/attributes/{attributeId}:
    delete:
      summary: Attribut von Maschine entfernen
      parameters:
        - $ref: "#/components/parameters/id"
        - name: attributeId
          in: path
          required: true
          schema:
            type: integer
      responses:
        204:
          description: Attribut gelöscht

  /templates:
    get:
      summary: Alle Templates auflisten
      responses:
        200:
          description: OK
    post:
      summary: Neues Template erstellen
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateMachineTemplateDto"
      responses:
        201:
          description: Erstellt

  /templates/{id}:
    get:
      summary: Einzelnes Template anzeigen
      parameters:
        - $ref: "#/components/parameters/id"
      responses:
        200:
          description: OK
    delete:
      summary: Template löschen
      parameters:
        - $ref: "#/components/parameters/id"
      responses:
        204:
          description: Gelöscht

  /templates/{id}/attributes:
    post:
      summary: Attribut zum Template hinzufügen
      parameters:
        - $ref: "#/components/parameters/id"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateAttributeInTemplateDto"
      responses:
        201:
          description: Attribut hinzugefügt

  /templates/{id}/attributes/{attrId}:
    delete:
      summary: Template-Attribut löschen
      parameters:
        - $ref: "#/components/parameters/id"
        - name: attrId
          in: path
          required: true
          schema:
            type: integer
      responses:
        204:
          description: Attribut gelöscht

components:
  parameters:
    id:
      name: id
      in: path
      required: true
      schema:
        type: integer

  schemas:
    CreateMachineDto:
      type: object
      required:
        - name
      properties:
        name:
          type: string

    CreateMachineTemplateDto:
      type: object
      required:
        - templateName
      properties:
        templateName:
          type: string

    CreateMachineAttributeDto:
      type: object
      required:
        - attributeName
        - type
        - attributeValue
      properties:
        attributeName:
          type: string
        type:
          type: string
          enum: [STRING, INTEGER, FLOAT, BOOLEAN]
        attributeValue:
          type: string

    CreateAttributeInTemplateDto:
      type: object
      required:
        - attributeInTemplateName
        - attributeInTemplateType
      properties:
        attributeInTemplateName:
          type: string
        attributeInTemplateType:
          type: string
          enum: [STRING, INTEGER, FLOAT, BOOLEAN]
