# Verwende Java 21
FROM eclipse-temurin:21-jdk

# Setze Arbeitsverzeichnis im Container
WORKDIR /app

# Kopiere das gebaute JAR aus dem Unterordner in den Container
COPY target/machine-management-0.0.1-SNAPSHOT.jar app.jar

# Exponiere Port
EXPOSE 8080

# Starte das Backend
ENTRYPOINT ["java", "-jar", "app.jar"]
